### ISSUE TITLE
I need help so i can backup my db file in this Flet app that runs on Android 14: I don't know if it's a problem with permissions in Android

### ISSUE THREAD

**Issue by LARM-TECHs** [Flet/flet#1]

**Comment by LARM-TECHs** [comment]
This code creates .csv files when FilePickers open but it is created empty. Some help please

def exportar_base_datos(self):
        fecha_actual = datetime.datetime.now().strftime('%Y-%m-%d')
        nombre_archivo = f"db_backup{fecha_actual}.csv"
        self.save_file_dialog.save_file(file_name=nombre_archivo)

    def save_file_result(self, e: ft.FilePickerResultEvent):
        if e.path:
            # Exportar a CSV
            with open(e.path, mode='w', newline='') as file:
                writer = csv.writer(file)
                writer.writerow(["CÓDIGO", "CANTIDAD", "FECHA"])
                productos = self.db_manager.fetch_productos()
                for producto in productos:
                    writer.writerow(producto)

            self.page.add(ft.SnackBar(ft.Text("Base de datos exportada a CSV correctamente."), open=True))
            self.page.update()

**Comment by Flet** [comment]
wrong repo?

**Comment by LARM-TECHs** [comment]
sorry
